### ISSUE TITLE
what changes you make on whisper_openAI?

### ISSUE THREAD

**Issue by DinukaGunaratne** [Srijith-rkr/WHISPERing-LLaMA#10]
Hi @Srijith-rkr , I saw you cloned whisper_openAI, not installing in, and I wonder what changes you made to this library? Also using Large-v2 lead to OOM on my machine (24gb VRAM), any advice?

**Comment by DinukaGunaratne** [comment]
is there pretrained weights for this repo?

**Comment by huckiyang** [comment]
Yes, there is weights for this repo as in https://github.com/Srijith-rkr/Whispering-LLaMA/blob/main/README.md#model-weights

- https://huggingface.co/Srijith-rkr/Whispering-LLaMA

> changes you made to this library?

at the time we worked on this project, there is no beam searching algorithm and temp based decoding. I guess the modification might be on this part. @Srijith-rkr any thoughts?

**Comment by Srijith-rkr** [comment]
In the paper, we generate multiple hypothesis in the from Whisper model to use as a prompt input to the LLM. We modified the beam search in the Whisper code to select the next token based on temperature sampling, to generate multiple candidates that do not capture the utterance very well. We do this to model a weak acoustic model for the LLM to improve upon. 

You can get the Whisper model weights with just 
import whisper
model = whisper.load_model("mention size")

When we wrote the paper, we did not have an instruction tuned model, so we used alpaca weights. And the weights of that model converted to lit-llama (the repo our code is built on) format is attached in https://huggingface.co/Srijith-rkr/Whispering-LLaMA

We also shared our dataset [here](https://huggingface.co/datasets/PeacefulData/HyPoradise-v1-GigaSpeech)

Regarding OOM for using Large-V2.
We also have a baseline using Whisper Tiny in the paper, but I don't think you will be able to finetune LLaMA 7B even then. We used 2 A100s (80GB VRAM)

You will be able to run LLaMA inference with 24GB VRAM with quantization.  

I hope that help you. Feel free to reopen this if you have any questions.

**Comment by rrscholarship** [comment]
Thank you for your reply.
Another question, if I would like to use other dataset, how do I get array of that audio? how is it calcualted? Thanks

 'audio': 
        {
            # in streaming mode 'path' will be 'xs_chunks_0000/YOU0000000315_S0000660.wav'
            'path': '/home/user/.cache/huggingface/datasets/downloads/extracted/9d48cf31/xs_chunks_0000/YOU0000000315_S0000660.wav', 
            'array': array([0.0005188 , 0.00085449, 0.00012207, ..., 0.00125122, 0.00076294, 0.00036621], dtype=float32), 
            'sampling_rate': 16000
        },

**Comment by DinukaGunaratne** [comment]
Thank you for your reply, its really helpful @Srijith-rkr! One last question, I still quite confused how it alpaca work as "ASR selector" prompt, if there no instruction tuned model? Also I did not find prompt for "ASR selector" in code base, does it mean alpaca weight is already finetuned insturction as "ASR selector"?
