### ISSUE TITLE
spell check

### ISSUE THREAD

**Issue by Sri-Tharun-FullStackDev** [Srijith-rkr/WHISPERing-LLaMA#7]
"Langugae" to be changed as "langauge"

in the below given stanza:

ASR Generative Error Correction by leveraging foundational Audio (Whisper) and **Langugae** (LLaMA) models.

**Comment by Srijith-rkr** [comment]
Hi Tharun, 

Thanks for sharing, I have updated the readme.

**Comment by Sri-Tharun-FullStackDev** [comment]
hi srijith,

good to hear, where are you ?
